-- MySQL Script generated by MySQL Workbench
-- Mon Dec 20 18:49:38 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Klient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Klient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Klient` (
  `id_klient` INT NOT NULL,
  `imie` VARCHAR(20) NULL,
  `nazwisko` VARCHAR(40) NULL,
  `rok_urodzenia` DATE NULL,
  `login` VARCHAR(40) NULL,
  `haslo_hash` VARCHAR(64) NULL,
  `rola` VARCHAR(1) NULL,
  `data_rejestracji` DATE NULL,
  `e_mail` VARCHAR(75) NULL,
  PRIMARY KEY (`id_klient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Platnosc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Platnosc` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Platnosc` (
  `id_platnosc` INT NOT NULL,
  `id_klient` INT NOT NULL,
  `numer_karty` VARCHAR(16) NULL,
  `rok_karty` DATE NULL,
  `cvc_karty` INT NULL,
  `data_platnosci` DATE NULL,
  `nr_konta_bankowego` VARCHAR(26) NULL,
  `czy_platnosc_dokonana` VARCHAR(3) NULL,
  PRIMARY KEY (`id_platnosc`),
  CONSTRAINT `fk_Platnosc_Klient`
    FOREIGN KEY (`id_klient`)
    REFERENCES `mydb`.`Klient` (`id_klient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Platnosc_Klient_idx` ON `mydb`.`Platnosc` (`id_klient` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Portfel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Portfel` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Portfel` (
  `id_portfel` INT NOT NULL,
  `id_klient` INT NOT NULL,
  `stan_konta` DECIMAL(10,2) NULL,
  `wspolczynnik_przyrostu` DECIMAL(10,2) NULL,
  `stawka` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id_portfel`),
  CONSTRAINT `fk_Portfel_Klient1`
    FOREIGN KEY (`id_klient`)
    REFERENCES `mydb`.`Klient` (`id_klient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Portfel_Klient1_idx` ON `mydb`.`Portfel` (`id_klient` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
